id: P006642
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:24.556118
source_metadata:
  id: bdr:W3CN8305
  title: དམངས་གླུ་ཆུ་མིག་དགུ་སྒྲིལ།
  author: ''
  volumes:
    f7b63cb96ac744098d3a9c52836b081e:
      image_group_id: I3CN8307
      title: ''
      volume_number: 1
      total_pages: 201
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
